### PR TITLE
Create the most basic version of the project#12

### PR DESCRIPTION
**Pull request by khmdagal**
Opened PR for Ticket #12

### CODE REVIEW

**Review by JihadOmer — APPROVED** [review]
Excellent !! Thank you

**Comment by salehpirouzi-cyf** [comment]
Hi @khmdagal @JihadOmer @Shimaadnan @Doris-Siu 

Are you sure after merging this PR to main repo, if I go to 'https://starter-kit-slji.onrender.com/admin' or 'https://starter-kit-slji.onrender.com/page1' or 'https://starter-kit-slji.onrender.com/page2' I would see your newly added components?

Also, when you are the last approver of a PR, you need to merge it. For instance, you agreed on having 1 approver. That means, Jihad had to merge after the approval. If you agree to have at least 2 approvers, when Jihad approved, next person should review > approve > merge

**Comment by salehpirouzi-cyf** [comment]
One more note.
@khmdagal named the branch to be 'khadar'. This is not a good practice for many reasons:

- What if khadar wants to stop working on this ticket in the middle of the work? should other person work on 'khadar'? should they create another branch?
- What if khadar wants to work on another task while waiting for this to be reviewed? should he create another branch with the same name?
- ...

Always name the branch in a way which is related to the feature/ticket and unrelated to 'assignee'
for instance, in this case you could name the branch: `issue12` or `basic-website` or `initial-commit` or ...
in future you might learn about different conventions to name a branch. it varies from one team to another

**Comment by khmdagal** [comment]
Thanks @salehpirouzi-cyf got that.

**Pull request merged**
